services:
  web:
    image: nginx:alpine
    volumes:
      - /var/lib/docker/volumes/portainer_data/_data/compose/49:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: nginx_proxy-net
