services:
  web:
    image: nginx:alpine
    volumes:
      - ./app/static:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - proxy

  api:
    build: ./app
    restart: unless-stopped
    networks:
      - proxy
    # nur nötig, falls Python-Backend (Flask/FastAPI) mitläuft

networks:
  proxy:
    external: true # dasselbe Netzwerk wie dein Nginx Proxy Manager
