services:
  web:
    image: nginx:alpine
    volumes:
      - /var/lib/docker/volumes/portainer_data/_data/compose/51:/usr/share/nginx/html:ro
      - /var/lib/docker/volumes/portainer_data/_data/compose/51/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: nginx_proxy-net
